In [12]:
from __future__ import division#计算数学模型 P28 双层玻璃的传导
from sympy import *
Q, k1,k2,T1,T2,d,l,Ta,Tb = symbols('Q  k1 k2 T1 T2 d l Ta Tb')
solve([Eq(Q,k1*(T1-Ta)/d ), Eq(Q,k2*(Ta-Tb)/l ),Eq(Q,k1*(Tb-T2)/d ) ],{Q,Ta  ,Tb})

{Ta: (T1*(d*k2 + k1*l) + T2*d*k2)/(2*d*k2 + k1*l),
 Tb: (T1*d*k2 + T2*(d*k2 + k1*l))/(2*d*k2 + k1*l),
 Q: k1*k2*(T1 - T2)/(2*d*k2 + k1*l)}

In [13]:
 Q= k1*k2*(T1 - T2)/(2*d*k2 + k1*l)

#计算数学模型 P28 双层玻璃的传导

In [ ]:
#计算数学模型 P10  药物吸收

In [19]:
from sympy import *
f = Function('f')
x = Symbol('x')
h = Symbol('h')
expr=dsolve(diff(f(x),x) + h*f(x),f(x))
#expr.subs(C1,1100)
print(expr)
#print (dsolve(diff(f(x),x) + h*f(x),f(x)))


Eq(f(x), C1*exp(-h*x))


In [38]:
from sympy import *
f = Function('f')
g = Function('g')
t = Symbol('t')
#h = Symbol('h')
#u = Symbol('u')
var('h u')
#g=1100*exp(-h*t)
h=0.1386
u=0.1155
expr=dsolve(diff(f(t),t) - h*(1100*exp(-h*t)) + u*f(t),f(t))
#expr.subs(C1,1100)
print(expr)

Eq(f(t), (C1 - 6600.0*exp(-0.0231*t))*exp(-0.1155*t))


In [39]:
diff(1100*h*(exp(-u*t)-exp(-h*t))/(h-u),t)

914.76*exp(-0.1386*t) - 762.3*exp(-0.1155*t)

In [40]:
h*1100*exp(-h*t)-u*(1100*h*(exp(-u*t)-exp(-h*t))/(h-u))


914.76*exp(-0.1386*t) - 762.3*exp(-0.1155*t)

In [41]:
x=1100*exp(-h*t)

In [42]:
x

1100*exp(-0.1386*t)

In [44]:
print(dsolve(diff(f(t),t) - h*(x) + u*f(t),f(t))

)

Eq(f(t), (C1 - 6600.0*exp(-0.0231*t))*exp(-0.1155*t))


In [117]:
from sympy import *
t=0
C1=Symbol('C1')
#y=(C1 - 6600.0*exp(-0.0231*t))*exp(-0.1155*t)
solve((C1 - 6600.0*exp(-0.0231*t))*exp(-0.1155*t),C1)

[6600.00000000000]

In [ ]:
from pylab import *  
  
figure(figsize=(8,5), dpi=80)  
 
x = np.linspace(0, 24,25, endpoint=True)  
 
Y1=(6600 - 6600.0*exp(-0.0231*x))*exp(-0.1155*x) 
Y2=6600.0*(-1*exp(-0.13861*x)+exp(-0.1155*x)  )  
X1=1100*exp(-h*x) 
plot(x, Y1 )  

plot(x, Y2 )  
plot(x, X1) 
show()   

In [95]:
x = np.linspace(0, 24,25, endpoint=True) 
apart((6600 - 6600.0*exp(-0.0231*x))*exp(-0.1155*x))

array([   0.        ,  134.2729274 ,  236.52132678,  312.48755706,
        366.99651143,  404.09336832,  427.16144055,  439.02292474,
        442.02496549,  438.11311454,  428.89397622,  415.68858121,
        399.5778156 ,  381.44104652,  361.9889257 ,  341.79121416,
        321.30035256,  300.87139881,  280.77886693,  261.23092445,
        242.38134087,  224.33952292,  207.1789244 ,  190.94407655,
        175.65644916])

In [96]:
apart(6600.0*(-1*exp(-0.13861*x)+exp(-0.1155*x)  )  )

array([   0.        ,  134.33038514,  236.62136897,  312.61819792,
        367.14815444,  404.25838848,  427.33383484,  439.19801995,
        442.19917459,  438.28373377,  429.05901655,  415.84662862,
        399.72791555,  381.58260871,  362.12164575,  341.91500953,
        321.41531017,  300.9777326 ,  280.87688349,  261.3209955 ,
        242.4638812 ,  224.41497307,  207.24773702,  191.0067059 ,
        175.71334309])

In [102]:
 xp(-0.0231*x) *exp(-0.1155*x) 

array([   0.        ,  134.2729274 ,  236.52132678,  312.48755706,
        366.99651143,  404.09336832,  427.16144055,  439.02292474,
        442.02496549,  438.11311454,  428.89397622,  415.68858121,
        399.5778156 ,  381.44104652,  361.9889257 ,  341.79121416,
        321.30035256,  300.87139881,  280.77886693,  261.23092445,
        242.38134087,  224.33952292,  207.1789244 ,  190.94407655,
        175.65644916])

In [122]:
#P37 
S=Symbol('S')
l=Symbol('l')
solve(diff((126480+500*l+260400/l),l),l)

[-2*sqrt(3255)/5, 2*sqrt(3255)/5]

In [135]:
print("l=%f "  % (2*sqrt(3255)/5))

l=22.821043 


In [136]:
l=(2*sqrt(3255)/5)
S=(126480+500*l+260400/l)
print("%f" % S)

149301.042921


In [148]:
#P40
N,t0,c,v,d3,d4=symbols('N t0 c v d3 d4')
N=1000/(
t0/3.6 +c*v+(d3+d4)/v

) 
vv=solve(diff(N  ,v) ,v)[1]  #获取正根
print (vv)

sqrt((d3 + d4)/c)


In [149]:
N.subs(v,vv)# 替换

1000/(c*sqrt((d3 + d4)/c) + 0.277777777777778*t0 + (d3 + d4)/sqrt((d3 + d4)/c))

In [151]:
simplify(N.subs(v,vv))

1000.0*sqrt((d3 + d4)/c)/(2.0*d3 + 2.0*d4 + 0.277777777777778*t0*sqrt((d3 + d4)/c))

In [152]:
pprint(simplify(N.subs(v,vv)))

                           _________                
                          ╱ d₃ + d₄                 
                1000.0⋅  ╱  ───────                 
                       ╲╱      c                    
────────────────────────────────────────────────────
                                           _________
                                          ╱ d₃ + d₄ 
2.0⋅d₃ + 2.0⋅d₄ + 0.277777777777778⋅t₀⋅  ╱  ─────── 
                                       ╲╱      c    
