In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [2]:
s = pd.Series([1,3,5,np.nan,6,8])
print(s)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64


In [3]:
index = pd.date_range('1/1/2000', periods=8)
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
df = pd.DataFrame(np.random.randn(8, 3), index=index,     columns=['A', 'B', 'C'])
wp = pd.Panel(np.random.randn(2, 5, 4), items=['Item1', 'Item2'],
                     major_axis=pd.date_range('1/1/2000', periods=5),
                    minor_axis=['A', 'B', 'C', 'D'])


In [4]:
long_series = pd.Series(np.random.randn(1000))
long_series.head()

0    0.238996
1    1.122561
2   -1.646274
3   -1.256083
4   -0.210890
dtype: float64

In [5]:
long_series.tail(3)

997   -1.012466
998    1.145694
999    0.866965
dtype: float64

In [6]:
index

DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04',
               '2000-01-05', '2000-01-06', '2000-01-07', '2000-01-08'],
              dtype='datetime64[ns]', freq='D')

In [14]:
df

A         B         C
2000-01-01  0.638562  1.367168  1.630254
2000-01-02 -1.664399  1.208549 -0.732545
2000-01-03  0.741615  0.851377 -2.131227
2000-01-04  1.843695 -0.608249 -0.575593
2000-01-05 -1.130195  0.711441  1.369132
2000-01-06  2.502983 -0.121143 -1.211406
2000-01-07 -1.056357 -0.842221 -0.445611
2000-01-08  1.120347  1.633088  0.911592

In [12]:
 df[:2]

A         B         C
2000-01-01  0.638562  1.367168  1.630254
2000-01-02 -1.664399  1.208549 -0.732545

In [13]:
s.values

array([ 0.92161905,  1.25541524, -0.67881173,  0.29775773, -1.21830518])

In [15]:
df.values

array([[ 0.63856185,  1.36716768,  1.63025364],
       [-1.66439926,  1.20854915, -0.73254464],
       [ 0.74161457,  0.85137658, -2.13122711],
       [ 1.84369494, -0.6082491 , -0.57559329],
       [-1.13019454,  0.71144074,  1.36913215],
       [ 2.50298332, -0.1211427 , -1.21140637],
       [-1.05635652, -0.84222142, -0.4456105 ],
       [ 1.1203473 ,  1.63308765,  0.91159185]])

In [16]:
wp.values

array([[[ 0.97739921,  0.15962509,  0.11222533, -0.86637784],
        [ 0.78974522, -1.84587918, -0.5346931 ,  0.092325  ],
        [-1.05084199,  1.09818974,  0.22542646, -0.45043799],
        [ 0.20777773,  0.60510059, -1.26354301, -0.06000344],
        [-1.03088838,  0.04685738,  1.24005616,  0.71950743]],

       [[-0.20844782,  0.65205519,  1.10789866,  0.69539223],
        [-0.65799485, -2.01355517,  0.79344069,  1.00532846],
        [ 0.85175969, -1.36091649,  0.81642343,  0.60208695],
        [ 0.53185457,  1.18268561,  1.33701348, -1.37438181],
        [ 0.36918057, -0.73656628,  0.87787475, -0.95534911]]])

In [23]:
row=df.iloc[1]
row

A   -1.664399
B    1.208549
C   -0.732545
Name: 2000-01-02 00:00:00, dtype: float64

In [24]:
column=df['A']
column

2000-01-01    0.638562
2000-01-02   -1.664399
2000-01-03    0.741615
2000-01-04    1.843695
2000-01-05   -1.130195
2000-01-06    2.502983
2000-01-07   -1.056357
2000-01-08    1.120347
Freq: D, Name: A, dtype: float64

In [26]:
df.sub(row, axis='columns')

A         B         C
2000-01-01  2.302961  0.158619  2.362798
2000-01-02  0.000000  0.000000  0.000000
2000-01-03  2.406014 -0.357173 -1.398682
2000-01-04  3.508094 -1.816798  0.156951
2000-01-05  0.534205 -0.497108  2.101677
2000-01-06  4.167383 -1.329692 -0.478862
2000-01-07  0.608043 -2.050771  0.286934
2000-01-08  2.784747  0.424538  1.644136

In [27]:
df

A         B         C
2000-01-01  0.638562  1.367168  1.630254
2000-01-02 -1.664399  1.208549 -0.732545
2000-01-03  0.741615  0.851377 -2.131227
2000-01-04  1.843695 -0.608249 -0.575593
2000-01-05 -1.130195  0.711441  1.369132
2000-01-06  2.502983 -0.121143 -1.211406
2000-01-07 -1.056357 -0.842221 -0.445611
2000-01-08  1.120347  1.633088  0.911592

In [28]:
df.sub(row, axis=1)

A         B         C
2000-01-01  2.302961  0.158619  2.362798
2000-01-02  0.000000  0.000000  0.000000
2000-01-03  2.406014 -0.357173 -1.398682
2000-01-04  3.508094 -1.816798  0.156951
2000-01-05  0.534205 -0.497108  2.101677
2000-01-06  4.167383 -1.329692 -0.478862
2000-01-07  0.608043 -2.050771  0.286934
2000-01-08  2.784747  0.424538  1.644136

In [29]:
 df.sub(column, axis='index')

A         B         C
2000-01-01  0.0  0.728606  0.991692
2000-01-02  0.0  2.872948  0.931855
2000-01-03  0.0  0.109762 -2.872842
2000-01-04  0.0 -2.451944 -2.419288
2000-01-05  0.0  1.841635  2.499327
2000-01-06  0.0 -2.624126 -3.714390
2000-01-07  0.0  0.214135  0.610746
2000-01-08  0.0  0.512740 -0.208755

In [32]:
df.sub(column, axis=0)  #列运行  行列式消元?

A         B         C
2000-01-01  0.0  0.728606  0.991692
2000-01-02  0.0  2.872948  0.931855
2000-01-03  0.0  0.109762 -2.872842
2000-01-04  0.0 -2.451944 -2.419288
2000-01-05  0.0  1.841635  2.499327
2000-01-06  0.0 -2.624126 -3.714390
2000-01-07  0.0  0.214135  0.610746
2000-01-08  0.0  0.512740 -0.208755

In [38]:
dfmi = df.copy()
dfmi.index = pd.MultiIndex.from_tuples([(1,'a'),(1,'b'),(1,'c'),(2,'a'),(2,'b'),(2,'c'),(3,'a'),(3,'b')],  names=['first','second'])
#
dfmi

A         B         C
first second                              
1     a       0.638562  1.367168  1.630254
      b      -1.664399  1.208549 -0.732545
      c       0.741615  0.851377 -2.131227
2     a       1.843695 -0.608249 -0.575593
      b      -1.130195  0.711441  1.369132
      c       2.502983 -0.121143 -1.211406
3     a      -1.056357 -0.842221 -0.445611
      b       1.120347  1.633088  0.911592

In [44]:
column=dfmi['A']
column
dfmi.sub(column, axis=0, level='second')


A         B         C
first second                         
1     a       0.0  0.728606  0.991692
      b       0.0  2.872948  0.931855
      c       0.0  0.109762 -2.872842
2     a       0.0 -2.451944 -2.419288
      b       0.0  1.841635  2.499327
      c       0.0 -2.624126 -3.714390
3     a       0.0  0.214135  0.610746
      b       0.0  0.512740 -0.208755

In [49]:
wp = pd.Panel(np.random.randn(2, 5, 4), items=['Item1', 'Item2'],
                     major_axis=pd.date_range('1/1/2000', periods=5),
                    minor_axis=['A', 'B', 'C', 'D'   ])

major_mean = wp.mean(axis='major') #列 平均
major_mean

Item1     Item2
A  0.305834  0.009316
B  0.280978  0.008625
C  0.298830 -0.150493
D  0.253982 -0.334119

In [54]:
wp.values

array([[[ 0.82482562,  0.19306395,  0.36327994, -0.94100309],
        [ 1.5431597 , -0.57134369,  2.21699476,  0.58236095],
        [ 0.9129023 ,  1.4544677 ,  0.49303729, -0.29641062],
        [ 0.0648286 ,  0.28971292, -1.00921178,  0.2244863 ],
        [-1.81654581,  0.03899062, -0.56995037,  1.70047858]],

       [[ 0.81010523,  0.43166856,  0.92720714, -1.2722515 ],
        [ 0.02595071,  1.25902557, -0.22656435, -0.4895159 ],
        [-1.65951071, -0.29259023, -1.21930618,  0.66397363],
        [ 1.12594909,  0.49896053,  0.59737641, -0.20681353],
        [-0.25591669, -1.85394188, -0.83117669, -0.36598533]]])

In [55]:
major_sum = wp.sum(axis='major') #列 
major_sum

Item1     Item2
A  1.529170  0.046578
B  1.404892  0.043123
C  1.494150 -0.752464
D  1.269912 -1.670593

In [56]:
item_sum=wp.sum(axis='items')
item_sum

A         B         C         D
2000-01-01  1.634931  0.624733  1.290487 -2.213255
2000-01-02  1.569110  0.687682  1.990430  0.092845
2000-01-03 -0.746608  1.161877 -0.726269  0.367563
2000-01-04  1.190778  0.788673 -0.411835  0.017673
2000-01-05 -2.072462 -1.814951 -1.401127  1.334493

In [71]:
s = pd.Series(np.arange(10),index=np.arange(1 ,11)) ;s

1     0
2     1
3     2
4     3
5     4
6     5
7     6
8     7
9     8
10    9
dtype: int32

In [67]:
np.arange(1,11)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
div, rem = divmod(s, 3)

In [76]:
div 

1     0
2     0
3     0
4     1
5     1
6     1
7     2
8     2
9     2
10    3
dtype: int32

In [75]:
rem

1     0
2     1
3     2
4     0
5     1
6     2
7     0
8     1
9     2
10    0
dtype: int32

In [77]:
div, rem = divmod(s, [2, 2, 3, 3, 4, 4, 5, 5, 6, 6])

In [78]:
div 

1     0
2     0
3     0
4     1
5     1
6     1
7     1
8     1
9     1
10    1
dtype: int32

In [79]:
rem

1     0
2     1
3     2
4     0
5     0
6     1
7     1
8     2
9     2
10    3
dtype: int32

In [82]:
df=pd.DataFrame(np.random.randn(4, 3), index=[1,2,3,4],     columns=['A', 'B', 'C'])
df1=pd.DataFrame(np.random.randn(4, 3), index=[1,2,3,4],     columns=['A', 'B', 'C'])

In [109]:
df

A         B         C
1  1.104122  0.441759  0.713261
2       NaN  0.881016  0.467958
3  1.317195 -0.823937 -1.353954
4 -0.527628 -0.946332  0.109308

In [84]:
df1

A         B         C
1  0.449095  0.144184  0.992328
2  0.314902 -0.569530  0.226143
3 -0.493469 -1.011438  2.516481
4  0.470547 -0.373832  0.856024

In [85]:
df+df1

A         B         C
1  1.553217  0.585943  1.705588
2  0.251392  0.311485  0.694102
3  0.823727 -1.835375  1.162527
4 -0.057081 -1.320164  0.965332

In [87]:
df.add(df1, fill_value=0)

A         B         C
1  1.553217  0.585943  1.705588
2  0.251392  0.311485  0.694102
3  0.823727 -1.835375  1.162527
4 -0.057081 -1.320164  0.965332

In [88]:
df

A         B         C
1  1.104122  0.441759  0.713261
2 -0.063511  0.881016  0.467958
3  1.317195 -0.823937 -1.353954
4 -0.527628 -0.946332  0.109308

In [89]:
df.gt(df1)

A      B      C
1   True   True  False
2  False   True   True
3   True   True  False
4  False  False  False

In [91]:
df1.ne(df)

A     B     C
1  True  True  True
2  True  True  True
3  True  True  True
4  True  True  True

In [107]:
(df > 0).all()

A    False
B    False
C    False
dtype: bool

In [93]:
(df > 0).any()

A    True
B    True
C    True
dtype: bool

In [94]:
(df > 0).any().any()

True

In [108]:
df.empty

False

In [114]:
df.empty

False

In [115]:
 df

A         B         C
1  1.104122  0.441759  0.713261
2       NaN  0.881016  0.467958
3  1.317195 -0.823937 -1.353954
4 -0.527628 -0.946332  0.109308

In [119]:
(df==0)

A      B      C
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False

In [120]:
 df1 = pd.DataFrame({'col':['foo', 0, np.nan]})

In [121]:
df1

col
0  foo
1    0
2  NaN

In [122]:
df2 = pd.DataFrame({'col':[np.nan, 0, 'foo']}, index=[2,1,0]) ;df2

col
2  NaN
1    0
0  foo

In [123]:
df2+df1

col
0  foofoo
1       0
2     NaN

In [124]:
df1.equals(df2.sort_index())

True

In [125]:
df2.sort_index()

col
0  foo
1    0
2  NaN

In [126]:
pd.Series(['foo', 'bar', 'baz'])

0    foo
1    bar
2    baz
dtype: object

In [127]:
pd.Index(['foo', 'bar', 'qux'])

Index(['foo', 'bar', 'qux'], dtype='object')

In [128]:
 df1 = pd.DataFrame({'A' : [1., np.nan, 3., 5., np.nan],
   ....:                     'B' : [np.nan, 2., 3., np.nan, 6.]})
 df2 = pd.DataFrame({'A' : [5., 2., 4., np.nan, 3., 7.],
   ....:                     'B' : [np.nan, np.nan, 3., 4., 6., 8.]})
   ....: 


In [129]:
df1

A    B
0  1.0  NaN
1  NaN  2.0
2  3.0  3.0
3  5.0  NaN
4  NaN  6.0

In [130]:
df2

A    B
0  5.0  NaN
1  2.0  NaN
2  4.0  3.0
3  NaN  4.0
4  3.0  6.0
5  7.0  8.0

In [131]:
 df1.combine_first(df2)  #蒙版  alpha

A    B
0  1.0  NaN
1  2.0  2.0
2  3.0  3.0
3  5.0  4.0
4  3.0  6.0
5  7.0  8.0

In [139]:
combiner = lambda x, y: np.where(pd.isnull(x), 100*y, x)
df1.combine(df2, combiner)

A      B
0    1.0    NaN
1  200.0    2.0
2    3.0    3.0
3    5.0  400.0
4  300.0    6.0
5  700.0  800.0

In [141]:
df1.cumsum()

A     B
0  1.0   NaN
1  NaN   2.0
2  4.0   5.0
3  9.0   NaN
4  NaN  11.0

In [142]:
df1.cumprod()  #连乘

A     B
0   1.0   NaN
1   NaN   2.0
2   3.0   6.0
3  15.0   NaN
4   NaN  36.0

In [146]:
df 

A         B         C
1  1.104122  0.441759  0.713261
2       NaN  0.881016  0.467958
3  1.317195 -0.823937 -1.353954
4 -0.527628 -0.946332  0.109308

In [147]:
df .cummin()

A         B         C
1  1.104122  0.441759  0.713261
2       NaN  0.441759  0.467958
3  1.104122 -0.823937 -1.353954
4 -0.527628 -0.946332 -1.353954

In [149]:
series = pd.Series(np.random.randn(50));series[20:50] = np.nan;series[10:20]  = 5 ;series

0    -0.637818
1    -0.434828
2    -0.899556
3     1.044554
4     0.372676
5    -0.690965
6     0.190678
7    -2.332009
8    -0.505337
9    -0.931794
10    5.000000
11    5.000000
12    5.000000
13    5.000000
14    5.000000
15    5.000000
16    5.000000
17    5.000000
18    5.000000
19    5.000000
20         NaN
21         NaN
22         NaN
23         NaN
24         NaN
25         NaN
26         NaN
27         NaN
28         NaN
29         NaN
30         NaN
31         NaN
32         NaN
33         NaN
34         NaN
35         NaN
36         NaN
37         NaN
38         NaN
39         NaN
40         NaN
41         NaN
42         NaN
43         NaN
44         NaN
45         NaN
46         NaN
47         NaN
48         NaN
49         NaN
dtype: float64

In [150]:
series.nunique()

11

In [156]:
series.describe()['75%']

5.0

In [155]:
series.describe()

count    20.000000
mean      2.258780
std       2.880689
min      -2.332009
25%      -0.538457
50%       3.022277
75%       5.000000
max       5.000000
dtype: float64

In [157]:
series.describe(percentiles=[.05, .25, .75, .95])

count    20.000000
mean      2.258780
std       2.880689
min      -2.332009
5%       -1.001804
25%      -0.538457
50%       3.022277
75%       5.000000
95%       5.000000
max       5.000000
dtype: float64

In [159]:
 s = pd.Series(['a', 'a', 'b', 'b', 'a', 'a', np.nan, 'c', 'd', 'a'])
s.describe()

count     9
unique    4
top       a
freq      5
dtype: object

In [161]:
frame = pd.DataFrame({'a': ['Yes', 'Yes', 'No', 'No'], 'b': range(4)})
frame.describe()

b
count  4.000000
mean   1.500000
std    1.290994
min    0.000000
25%    0.750000
50%    1.500000
75%    2.250000
max    3.000000

In [163]:
frame = pd.DataFrame({'a': ['Yes', 'Yes', 'No', 'No'], 'b': range(4)})
frame

a  b
0  Yes  0
1  Yes  1
2   No  2
3   No  3

In [164]:
 frame.describe(include=['object'])

a
count    4
unique   2
top     No
freq     2

In [165]:
frame.describe(include=['number'])

b
count  4.000000
mean   1.500000
std    1.290994
min    0.000000
25%    0.750000
50%    1.500000
75%    2.250000
max    3.000000

In [166]:
frame.describe(include='all')

a         b
count     4  4.000000
unique    2       NaN
top      No       NaN
freq      2       NaN
mean    NaN  1.500000
std     NaN  1.290994
min     NaN  0.000000
25%     NaN  0.750000
50%     NaN  1.500000
75%     NaN  2.250000
max     NaN  3.000000

In [167]:
s1 = pd.Series(np.random.randn(5))

In [168]:
s1.idxmin(), s1.idxmax()

(4, 0)

In [169]:
s1

0    1.432588
1   -0.465566
2    0.504141
3    1.249507
4   -1.064492
dtype: float64

In [170]:
df1 = pd.DataFrame(np.random.randn(5,3), columns=['A','B','C'])
df1

A         B         C
0  0.004865  1.803142 -0.329097
1  1.321968  0.415566  1.264769
2 -1.432342 -0.666858  1.985527
3 -0.729509 -0.500424 -0.602087
4 -0.627094 -1.365475  0.448081

In [171]:
 df1.idxmin(axis=0)

A    2
B    4
C    3
dtype: int64

In [172]:
df1.idxmax(axis=1)

0    B
1    A
2    C
3    B
4    C
dtype: object

In [173]:
df3 = pd.DataFrame([2, 1, 1, 3, np.nan], columns=['A'], index=list('edcba'))

In [174]:
df3

A
e  2.0
d  1.0
c  1.0
b  3.0
a  NaN

# Value counts (histogramming) / Mode

In [175]:
data = np.random.randint(0, 7, size=50)

In [176]:
data

array([0, 0, 1, 5, 3, 0, 5, 6, 2, 1, 6, 1, 6, 0, 3, 5, 2, 4, 3, 6, 2, 2, 0,
       4, 1, 0, 4, 4, 5, 1, 1, 4, 5, 0, 2, 6, 1, 2, 0, 2, 0, 3, 6, 6, 0, 5,
       4, 2, 2, 6])

In [177]:
s = pd.Series(data)

In [178]:
s.value_counts()

0    10
2     9
6     8
1     7
5     6
4     6
3     4
dtype: int64

In [179]:
pd.value_counts(data)

0    10
2     9
6     8
1     7
5     6
4     6
3     4
dtype: int64

In [180]:
s5 = pd.Series([1, 1, 3, 3, 3, 5, 5, 7, 7, 7]);s5.mode()

0    3
1    7
dtype: int64

In [190]:
df5 = pd.DataFrame({"A": np.random.randint(0, 7, size=10), "B": np.random.randint(-10, 15, size=10)})
df5 


A   B
0  6 -10
1  3   7
2  3  -8
3  0   3
4  0  -5
5  1  14
6  2  -1
7  0  -7
8  1  10
9  1   6

In [191]:
df5.mode()

A   B
0  0.0 -10
1  1.0  -8
2  NaN  -7
3  NaN  -5
4  NaN  -1
5  NaN   3
6  NaN   6
7  NaN   7
8  NaN  10
9  NaN  14

In [199]:
arr = np.random.randn(10)
arr

array([-1.02957557, -0.15743484,  1.64058301, -0.25673695,  0.39510723,
        1.07418393,  0.72281115,  1.36666799, -0.89950524,  0.30667084])

In [200]:
factor = pd.cut(arr, 4)
factor

[(-1.032, -0.362], (-0.362, 0.306], (0.973, 1.641], (-0.362, 0.306], (0.306, 0.973], (0.973, 1.641], (0.306, 0.973], (0.973, 1.641], (-1.032, -0.362], (0.306, 0.973]]
Categories (4, interval[float64]): [(-1.032, -0.362] < (-0.362, 0.306] < (0.306, 0.973] < (0.973, 1.641]]

In [198]:
factor = pd.cut(arr, [-5, -1, 0, 1, 5]);factor

[(1, 5], (0, 1], (-5, -1], (-1, 0], (-1, 0], ..., (0, 1], (-1, 0], (-1, 0], (0, 1], (-1, 0]]
Length: 20
Categories (4, interval[int64]): [(-5, -1] < (-1, 0] < (0, 1] < (1, 5]]

In [203]:
pd.Series(arr).describe()

count    10.000000
mean      0.316277
std       0.909536
min      -1.029576
25%      -0.231911
50%       0.350889
75%       0.986341
max       1.640583
dtype: float64

In [204]:
-0.362+1.032

0.67

In [207]:
 arr =[1,2,3,4,5,6,7,8,9]

 factor = pd.qcut(arr, [0, .25, .5, .75, 1])

 factor


[(0.999, 3.0], (0.999, 3.0], (0.999, 3.0], (3.0, 5.0], (3.0, 5.0], (5.0, 7.0], (5.0, 7.0], (7.0, 9.0], (7.0, 9.0]]
Categories (4, interval[float64]): [(0.999, 3.0] < (3.0, 5.0] < (5.0, 7.0] < (7.0, 9.0]]

In [208]:
 pd.value_counts(factor)  #区间分析

(0.999, 3.0]    3
(7.0, 9.0]      2
(5.0, 7.0]      2
(3.0, 5.0]      2
dtype: int64

In [215]:
df5.query('A>0')

A   B
0  6 -10
1  3   7
2  3  -8
5  1  14
6  2  -1
8  1  10
9  1   6

f:\anaconda3\envs\tensorflow\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: invalid value encountered in log
  if __name__ == '__main__':


A   B      ln_a
0  6 -10       NaN
1  3   7  1.945910
2  3  -8       NaN
5  1  14  2.639057
6  2  -1       NaN
8  1  10  2.302585
9  1   6  1.791759

In [224]:
df=df5.add(20,axis='columns')

In [230]:
df 

A   B
0  26  10
1  23  27
2  23  12
3  20  23
4  20  15
5  21  34
6  22  19
7  20  13
8  21  30
9  21  26

In [273]:
import statsmodels.formula.api as sm
from scipy import stats
ds=df.query('A>0').assign(ln_a=lambda df: np.log(df.B))

In [274]:
dd= ds.pipe((sm.poisson, 'data'), 'A ~ ln_a ').fit() 

Optimization terminated successfully.
         Current function value: 2.517865
         Iterations 25


In [277]:

dd.describe()

AttributeError: 'PoissonResults' object has no attribute 'describer'

In [258]:
from scipy import stats
stats.chi2.pdf(0, 1)
0.029846

0.029846

In [279]:
 stats.chi2.sf(16.919, 9)

0.049999640848349826

In [281]:
 stats.chi2.ppf(0.95, 9) #ppf：分位点函数（CDF的逆）

16.918977604620448

In [286]:
(12-(1.6551+8.6058))**2/(1.6551+8.6058)


0.2947566792386635

3078.27

In [287]:
 df.apply(np.mean)

A    21.7
B    20.9
dtype: float64

In [288]:
df.apply(np.mean, axis=1)

0    18.0
1    25.0
2    17.5
3    21.5
4    17.5
5    27.5
6    20.5
7    16.5
8    25.5
9    23.5
dtype: float64

In [289]:
df

A   B
0  26  10
1  23  27
2  23  12
3  20  23
4  20  15
5  21  34
6  22  19
7  20  13
8  21  30
9  21  26

In [290]:
df.apply(np.mean, axis=0)

A    21.7
B    20.9
dtype: float64

In [291]:
df.apply(lambda x: x.max() - x.min())

A     6
B    24
dtype: int64

In [292]:
df.apply(np.cumsum)

A    B
0   26   10
1   49   37
2   72   49
3   92   72
4  112   87
5  133  121
6  155  140
7  175  153
8  196  183
9  217  209

In [293]:
df.apply(np.exp)

A             B
0  1.957296e+11  2.202647e+04
1  9.744803e+09  5.320482e+11
2  9.744803e+09  1.627548e+05
3  4.851652e+08  9.744803e+09
4  4.851652e+08  3.269017e+06
5  1.318816e+09  5.834617e+14
6  3.584913e+09  1.784823e+08
7  4.851652e+08  4.424134e+05
8  1.318816e+09  1.068647e+13
9  1.318816e+09  1.957296e+11

In [297]:
tsdf = pd.DataFrame(np.random.randn(10, 3), columns=['A', 'B', 'C'],
   .....:                     index=pd.date_range('1/1/2000', periods=10))

In [298]:
tsdf.apply(lambda x: x.idxmax())

A   2000-01-07
B   2000-01-09
C   2000-01-01
dtype: datetime64[ns]

In [299]:
tsdf

A         B         C
2000-01-01  0.992800  1.532182  0.885388
2000-01-02 -0.501413  0.474629  0.856707
2000-01-03  0.097718 -0.228285 -0.846912
2000-01-04 -0.403162  1.352565 -1.090372
2000-01-05  0.316875  0.371028 -1.234373
2000-01-06  0.254885 -2.065865 -1.320129
2000-01-07  1.024413 -1.032586 -1.365807
2000-01-08 -1.477153 -0.007536 -0.890696
2000-01-09 -0.859515  1.881639  0.716051
2000-01-10  0.635642 -0.108492 -0.639738

In [301]:
def subtract_and_divide(x, sub, divide=1):
    return (x - sub) / divide
tsdf.apply(subtract_and_divide, args=(5,), divide=3)

A         B         C
2000-01-01 -1.335733 -1.155939 -1.371537
2000-01-02 -1.833804 -1.508457 -1.381098
2000-01-03 -1.634094 -1.742762 -1.948971
2000-01-04 -1.801054 -1.215812 -2.030124
2000-01-05 -1.561042 -1.542991 -2.078124
2000-01-06 -1.581705 -2.355288 -2.106710
2000-01-07 -1.325196 -2.010862 -2.121936
2000-01-08 -2.159051 -1.669179 -1.963565
2000-01-09 -1.953172 -1.039454 -1.427983
2000-01-10 -1.454786 -1.702831 -1.879913

In [302]:
 tsdf.apply(pd.Series.interpolate) #插入

A         B         C
2000-01-01  0.992800  1.532182  0.885388
2000-01-02 -0.501413  0.474629  0.856707
2000-01-03  0.097718 -0.228285 -0.846912
2000-01-04 -0.403162  1.352565 -1.090372
2000-01-05  0.316875  0.371028 -1.234373
2000-01-06  0.254885 -2.065865 -1.320129
2000-01-07  1.024413 -1.032586 -1.365807
2000-01-08 -1.477153 -0.007536 -0.890696
2000-01-09 -0.859515  1.881639  0.716051
2000-01-10  0.635642 -0.108492 -0.639738

In [303]:
tsdf.iloc[3:7] = np.nan


In [304]:
 tsdf

A         B         C
2000-01-01  0.992800  1.532182  0.885388
2000-01-02 -0.501413  0.474629  0.856707
2000-01-03  0.097718 -0.228285 -0.846912
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08 -1.477153 -0.007536 -0.890696
2000-01-09 -0.859515  1.881639  0.716051
2000-01-10  0.635642 -0.108492 -0.639738

In [305]:
 tsdf.apply(pd.Series.interpolate)

A         B         C
2000-01-01  0.992800  1.532182  0.885388
2000-01-02 -0.501413  0.474629  0.856707
2000-01-03  0.097718 -0.228285 -0.846912
2000-01-04 -0.217256 -0.184135 -0.855669
2000-01-05 -0.532230 -0.139985 -0.864425
2000-01-06 -0.847204 -0.095836 -0.873182
2000-01-07 -1.162179 -0.051686 -0.881939
2000-01-08 -1.477153 -0.007536 -0.890696
2000-01-09 -0.859515  1.881639  0.716051
2000-01-10  0.635642 -0.108492 -0.639738

In [306]:
 tsdf.agg(np.sum)

A   -1.111921
B    3.544137
C    0.080800
dtype: float64

In [307]:
 tsdf.agg('sum')

A   -1.111921
B    3.544137
C    0.080800
dtype: float64

In [308]:
 tsdf.sum()

A   -1.111921
B    3.544137
C    0.080800
dtype: float64

In [309]:
tsdf.A.agg('sum')

-1.111920555255113

In [310]:
 tsdf.agg(['sum'])

A         B       C
sum -1.111921  3.544137  0.0808

In [311]:
tsdf.agg(['sum', 'mean'])

A         B         C
sum  -1.111921  3.544137  0.080800
mean -0.185320  0.590689  0.013467

In [312]:
tsdf.A.agg(['sum', lambda x: x.mean()])

sum        -1.111921
<lambda>   -0.185320
Name: A, dtype: float64

In [313]:
 tsdf.agg({'A': 'mean', 'B': 'sum'})

B    3.544137
A   -0.185320
dtype: float64

In [314]:
tsdf.agg({'A': ['mean', 'min'], 'B': 'sum'})

B         A
mean       NaN -0.185320
min        NaN -1.477153
sum   3.544137       NaN

In [317]:
from functools import partial
q_25 = partial(pd.Series.quantile, q=0.25)
q_25.__name__ = '25%'
q_75 = partial(pd.Series.quantile, q=0.75)
q_75.__name__ = '75%'
q_50 = partial(pd.Series.quantile, q=0.50)
q_50.__name__ = '50%'
tsdf.agg(['count', 'mean', 'std', 'min', q_25, 'median',q_50, q_75, 'max'])

A         B         C
count   6.000000  6.000000  6.000000
mean   -0.185320  0.590689  0.013467
std     0.934382  0.903756  0.888748
min    -1.477153 -0.228285 -0.890696
25%    -0.769990 -0.083253 -0.795118
median -0.201847  0.233546  0.038156
50%    -0.201847  0.233546  0.038156
75%     0.501161  1.267794  0.821543
max     0.992800  1.881639  0.885388

In [316]:
 tsdf
    

A         B         C
2000-01-01  0.992800  1.532182  0.885388
2000-01-02 -0.501413  0.474629  0.856707
2000-01-03  0.097718 -0.228285 -0.846912
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08 -1.477153 -0.007536 -0.890696
2000-01-09 -0.859515  1.881639  0.716051
2000-01-10  0.635642 -0.108492 -0.639738

In [321]:
 tsdf.iloc[0:1]

A         B         C
2000-01-01  0.9928  1.532182  0.885388

In [322]:
tsdf.transform(np.abs)

A         B         C
2000-01-01  0.992800  1.532182  0.885388
2000-01-02  0.501413  0.474629  0.856707
2000-01-03  0.097718  0.228285  0.846912
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08  1.477153  0.007536  0.890696
2000-01-09  0.859515  1.881639  0.716051
2000-01-10  0.635642  0.108492  0.639738

In [323]:
tsdf.transform('abs')

A         B         C
2000-01-01  0.992800  1.532182  0.885388
2000-01-02  0.501413  0.474629  0.856707
2000-01-03  0.097718  0.228285  0.846912
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08  1.477153  0.007536  0.890696
2000-01-09  0.859515  1.881639  0.716051
2000-01-10  0.635642  0.108492  0.639738

In [324]:
np.abs(tsdf)

A         B         C
2000-01-01  0.992800  1.532182  0.885388
2000-01-02  0.501413  0.474629  0.856707
2000-01-03  0.097718  0.228285  0.846912
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08  1.477153  0.007536  0.890696
2000-01-09  0.859515  1.881639  0.716051
2000-01-10  0.635642  0.108492  0.639738

In [325]:
tsdf.A.transform([np.abs, lambda x: x+1])

absolute  <lambda>
2000-01-01  0.992800  1.992800
2000-01-02  0.501413  0.498587
2000-01-03  0.097718  1.097718
2000-01-04       NaN       NaN
2000-01-05       NaN       NaN
2000-01-06       NaN       NaN
2000-01-07       NaN       NaN
2000-01-08  1.477153 -0.477153
2000-01-09  0.859515  0.140485
2000-01-10  0.635642  1.635642

In [326]:
tsdf.transform({'A': np.abs, 'B': lambda x: x+1})

B         A
2000-01-01  2.532182  0.992800
2000-01-02  1.474629  0.501413
2000-01-03  0.771715  0.097718
2000-01-04       NaN       NaN
2000-01-05       NaN       NaN
2000-01-06       NaN       NaN
2000-01-07       NaN       NaN
2000-01-08  0.992464  1.477153
2000-01-09  2.881639  0.859515
2000-01-10  0.891508  0.635642

In [334]:
tsdf.transform({'A': np.abs, 'B': [lambda x: x+1, 'sqrt'], 'C': lambda x: x})

f:\anaconda3\envs\tensorflow\lib\site-packages\pandas\core\base.py:402: RuntimeWarning: invalid value encountered in sqrt
  return f(self, *args, **kwargs)


B                   C         A
            <lambda>      sqrt  <lambda>  absolute
2000-01-01  2.532182  1.237813  0.885388  0.992800
2000-01-02  1.474629  0.688933  0.856707  0.501413
2000-01-03  0.771715       NaN -0.846912  0.097718
2000-01-04       NaN       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN       NaN
2000-01-08  0.992464       NaN -0.890696  1.477153
2000-01-09  2.881639  1.371729  0.716051  0.859515
2000-01-10  0.891508       NaN -0.639738  0.635642

In [338]:
df1
 

A         B         C
0  0.004865  1.803142 -0.329097
1  1.321968  0.415566  1.264769
2 -1.432342 -0.666858  1.985527
3 -0.729509 -0.500424 -0.602087
4 -0.627094 -1.365475  0.448081

In [340]:
f = lambda x: len(str(x))
df1['A'].map(f)

0    20
1    18
2    19
3    18
4    19
Name: A, dtype: int64

In [341]:
df1.applymap(f)

A   B   C
0  20  18  19
1  18  19  18
2  19  19  17
3  18  19  19
4  19  19  18

In [342]:
g = lambda x:(str(x))
df1.applymap(g)

A                    B                    C
0  0.004865056571648514   1.8031420927159414  -0.3290972877170851
1    1.3219679135921194  0.41556618814340607   1.2647690826620483
2   -1.4323421921155615  -0.6668576688545697    1.985526621078404
3    -0.729508865002122  -0.5004244461168912  -0.6020873152947959
4   -0.6270943688430254  -1.3654745598738292   0.4480807794868013

In [355]:
"%4f  %5.3f" % (df1['A'][1], df1['A'][1])

'1.321968  1.322'

In [356]:
import pandas.util.testing as tm
panel = tm.makePanel(5)
panel

<class 'pandas.core.panel.Panel'>
Dimensions: 3 (items) x 5 (major_axis) x 4 (minor_axis)
Items axis: ItemA to ItemC
Major_axis axis: 2000-01-03 00:00:00 to 2000-01-07 00:00:00
Minor_axis axis: A to D

In [357]:
panel['ItemA']

A         B         C         D
2000-01-03 -0.833434 -0.632756  1.348337 -0.241354
2000-01-04  1.543090  0.791500 -0.580081 -1.523915
2000-01-05 -0.968614 -0.373158  0.470827  1.403003
2000-01-06  1.674353  0.361249 -1.585247  1.688947
2000-01-07 -0.405573 -2.577469  0.870823  0.882944

In [360]:
result = panel.apply(lambda x: x*2, axis='items')
result['ItemB']

A         B         C         D
2000-01-03  0.585304  2.389614  2.184986  0.929864
2000-01-04 -0.655687 -2.188032  0.041540 -0.184054
2000-01-05 -1.661485  3.405192 -1.089272 -2.575665
2000-01-06 -1.113037  3.253925 -0.293536  0.441165
2000-01-07  1.613181 -2.413208  2.004080  1.330859

In [371]:
result.loc['ItemA':'ItemC']

<class 'pandas.core.panel.Panel'>
Dimensions: 3 (items) x 5 (major_axis) x 4 (minor_axis)
Items axis: ItemA to ItemC
Major_axis axis: 2000-01-03 00:00:00 to 2000-01-07 00:00:00
Minor_axis axis: A to D