In [9]:
import numpy as np 
import scipy as sp
a=np.arange(5)
a.dtype


dtype('int32')

In [17]:
a=np.arange(9)
a[1:2][0:1]


array([1])

In [25]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
a[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

In [23]:
a[:7:2]

array([0, 2, 4, 6])

In [26]:
b=np.arange(24)

In [27]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [28]:
b.reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [31]:
b.reshape(2,4,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [40]:
c=b.reshape(2,4,3)



In [47]:
c[0,:,:]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [48]:
c[0,1,::2]

array([3, 5])

In [49]:
c[...,1]

array([[ 1,  4,  7, 10],
       [13, 16, 19, 22]])